spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-compose-mysql-1:3306/fif?serverTimezone=Asia/Seoul
    username: fridgeisfree
    password: fif123

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.default_batch_fetch_size: 100

ai-server-base-url: https://j10s005.p.ssafy.io/api/ai