spring:
  profiles:
    include:
      - deploy

#  # 사용자 인증: 필터 bean 재등록
#  main:
#    allow-bean-definition-overriding: true

AUTHORIZATION_HEADER_NAME: Authorization
AUTHORIZATION_TYPE: Bearer
JWT_SECRET_KEY: FridgeIsFreeIsFridgeFridgeIsFreeIsFridgeFridgeIsFreeIsFridgeSecret
ACCESS_TOKEN_EXPIRE_TIME_MILLI_SEC: 86400000 # 1일
REFRESH_TOKEN_EXPIRE_TIME_MILLI_SEC: 86400000 # 1일
REFRESH_TOKEN_NAME: refreshToken


# Swagger
springdoc:
  swagger-ui:
    path: /api/swagger-ui
    persist-authorization: true
  api-docs:
    path: /api/api-docs
  
# AWS
cloud:
  aws:
    s3:
      bucket: fridgeisfree
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIA53BIDTSEZHDIZAL3
      secret-key: 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